USE [master]
GO

/****** Object:  Database [STOCK]    Script Date: 2018/07/19 13:20:18 ******/
CREATE DATABASE [STOCK]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'STOCK', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\STOCK.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'STOCK_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\STOCK_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [STOCK] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [STOCK].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [STOCK] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [STOCK] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [STOCK] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [STOCK] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [STOCK] SET ARITHABORT OFF 
GO

ALTER DATABASE [STOCK] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [STOCK] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [STOCK] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [STOCK] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [STOCK] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [STOCK] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [STOCK] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [STOCK] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [STOCK] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [STOCK] SET  DISABLE_BROKER 
GO

ALTER DATABASE [STOCK] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [STOCK] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [STOCK] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [STOCK] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [STOCK] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [STOCK] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [STOCK] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [STOCK] SET RECOVERY FULL 
GO

ALTER DATABASE [STOCK] SET  MULTI_USER 
GO

ALTER DATABASE [STOCK] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [STOCK] SET DB_CHAINING OFF 
GO

ALTER DATABASE [STOCK] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [STOCK] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [STOCK] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [STOCK] SET QUERY_STORE = OFF
GO

USE [STOCK]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [STOCK] SET  READ_WRITE 
GO


